version: '3.9'
services:
  rpmbuilder:
    build: .
    platform: linux/amd64
    command:
    - bash
    - '-c'
    - 'while true; do sleep 1; done'
    volumes:
    - ./:/host
    - ./rpmbuilder/conf/github2spec.yaml:/usr/rpmbuilder/conf/github2spec.yaml
