services:
  specgen:
    build: .
    image: specgen
    command:
      - /host/scripts/generate_specs.sh
    volumes:
      - ./:/host
  rpmbuilder:
    image: specgen
    command:
      - /host/scripts/build_rpms.sh
    volumes:
      - ./:/host
  rpmdownloader:
    image: specgen
    command:
      - /host/scripts/download_rpms.sh
    volumes:
      - ./:/host
  rpmsigner:
    image: specgen
    environment:
      - GPG_PASSPHRASE
      - GPG_KEY
    command:
      - /host/scripts/sign_rpms.sh
    volumes:
      - ./:/host
