services:
  specgen:
    build:
      context: .
      dockerfile: Dockerfile.specgen
    command:
      - /host/scripts/generate_specs.sh
    volumes:
      - ./:/host
    environment:
      GITHUB2SPEC_CONFIG: /host/config/github2spec.yaml
  rpmbuilder:
    build: docker/rpmtools
    command:
      - /host/scripts/build_rpms.sh
    volumes:
      - ./:/host
  rpmdownloader:
    build: docker/rpmtools
    command:
      - /host/scripts/download_rpms.sh
    volumes:
      - ./:/host
  rpmsigner:
    build: docker/rpmtools
    environment:
      - GPG_PASSPHRASE
      - GPG_KEY
    command:
      - /host/scripts/sign_rpms.sh
    volumes:
      - ./:/host
