services:
  specgen:
    build:
      context: .
      dockerfile: docker/specgen/Dockerfile
    command:
      - /host/scripts/generate_specs.sh
    volumes:
      - ./:/host
  rpmbuilder:
    build: docker/rpmtools
    command:
      - /host/scripts/build_rpms.sh
    volumes:
      - ./:/host
  rpmdownloader:
    build: docker/rpmtools
    command:
      - /host/scripts/download_rpms.sh
    volumes:
      - ./:/host
  rpmsigner:
    build: docker/rpmtools
    environment:
      - GPG_PASSPHRASE
      - GPG_KEY
    command:
      - /host/scripts/sign_rpms.sh
    volumes:
      - ./:/host
