template: ./rpmbuilder/templates/spec.j2
dest: specs/
repositories:
  pgfga:
    organization: mannemsolutions
    asset_filter: '{{ repository }}_{{ version }}_linux_{{ binary_arch }}.tar.gz$'
    files:
      - src: '{{ repository }}'
        dest: '%{_bindir}/{{ repository }}'
        mode: '0755'
  pgav:
    organization: mannemsolutions
    asset_filter: '{{ repository }}_{{ version }}_Linux-{{ package_arch }}.tar.gz$'
    files:
      - src: '{{ repository }}'
        dest: '%{_bindir}/{{ repository }}'
        mode: '0755'
  pgroute66:
    organization: mannemsolutions
    asset_filter: '{{ repository }}_{{ version }}_linux_{{ binary_arch }}.tar.gz$'
    files:
      - src: '{{ repository }}'
        dest: '%{_bindir}/{{ repository }}'
        mode: '0755'
  pgquartz:
    organization: mannemsolutions
    asset_filter: '{{ repository }}_{{ version }}_linux_{{ binary_arch }}.tar.gz$'
    files:
      - src: '{{ repository }}'
        dest: '%{_bindir}/{{ repository }}'
        mode: '0755'
  stolon:
    organization: mannemsolutions
    asset_filter: '{{ repository }}_{{ version }}_linux_{{ binary_arch }}.tar.gz$'
    files:
      - src: 'stolonctl'
        dest: '%{_bindir}/stolonctl'
        mode: '0755'
      - src: 'stolon-sentinel'
        dest: '%{_bindir}/stolon-sentinel'
        mode: '0755'
      - src: 'stolon-proxy'
        dest: '%{_bindir}/stolon-proxy'
        mode: '0755'
      - src: 'stolon-keeper'
        dest: '%{_bindir}/stolon-keeper'
        mode: '0755'
  etcd:
    organization: etcd-io
    asset_filter: '{{ package_name }}-{{ version }}-linux-{{ binary_arch }}.tar.gz$'
    files:
      - src: 'etcd-{{ version }}-linux-{{ binary_arch }}/etcdctl'
        dest: '%{_bindir}/etcdctl'
        mode: '0755'
      - src: 'etcd-{{ version }}-linux-{{ binary_arch }}/etcd'
        dest: '%{_bindir}/etcd'
        mode: '0755'
