name: Release workflow for rpms
on:
  workflow_dispatch:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v0.2.19, v0.2.14a

jobs:
  build_rpms:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - arm64
          - amd64
    steps:
      - uses: actions/checkout@master
      - name: update to docker-compose v2
        run: |
          sudo apt-get install -y curl
          sudo curl -SL https://github.com/docker/compose/releases/download/v2.3.3/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
      - name: install compose
        run: |
          docker-compose --version
          echo $PGVERSION
      - name: generate specs
        run: docker-compose up specgen
      - name: build rpms
        run: docker-compose up rpmbuilder
      - name: download rpms
        run: docker-compose up rpmdownloader
      - name: sign rpms
        run: docker-compose up rpmsigner
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          GPG_KEY: ${{ GPG_KEY }}
      - name: Add to release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            rpms/*.rpm
            gpg_pubkey.asc
            LICENSE
            README.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
