name: Release workflow for rpms
on:
  workflow_dispatch:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v0.2.19, v0.2.14a

env:
  COMPOSE_DOCKER_CLI_BUILD: 1

jobs:
  build_rpms:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - arm64
          - amd64
    steps:
      - uses: actions/checkout@master
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: update to docker-compose v2
        run: |
          sudo apt-get install -y curl
          sudo curl -SL https://github.com/docker/compose/releases/download/v2.3.3/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
      - name: install compose
        run: |
          docker-compose --version
          echo $PGVERSION
      - name: create folders as required
        run: |
          mkdir specs rpms
          chmod 777 specs rpms
      - name: generate specs
        run: |
          docker-compose up specgen --exit-code-from specgen
        env:
          DOCKER_DEFAULT_PLATFORM: linux/${{ matrix.arch }}
          DOCKER_BUILDKIT: 1
      - name: build rpms
        run: docker-compose up rpmbuilder --exit-code-from rpmbuilder
        env:
          DOCKER_DEFAULT_PLATFORM: linux/${{ matrix.arch }}
          DOCKER_BUILDKIT: 1
      - name: sign rpms
        run: docker-compose up rpmsigner --exit-code-from rpmsigner
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          GPG_KEY: ${{ secrets.GPG_KEY }}
          DOCKER_DEFAULT_PLATFORM: linux/${{ matrix.arch }}
          DOCKER_BUILDKIT: 1
      - name: Add to release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            rpms/*.rpm
            gpg_pubkey.asc
            LICENSE
            README.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  download_rpms:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: update to docker-compose v2
        run: |
          sudo apt-get install -y curl
          sudo curl -SL https://github.com/docker/compose/releases/download/v2.3.3/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
      - name: install compose
        run: |
          docker-compose --version
          echo $PGVERSION
      - name: create folders as required
        run: |
          mkdir rpms
          chmod 777 rpms
      - name: download rpms
        run: docker-compose up rpmdownloader --exit-code-from rpmdownloader
      - name: sign rpms
        run: docker-compose up rpmsigner --exit-code-from rpmsigner
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          GPG_KEY: ${{ secrets.GPG_KEY }}
      - name: Add to release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            rpms/*.rpm
            gpg_pubkey.asc
            LICENSE
            README.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
