name: CI/CD for config changes
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: read

jobs:
  check_config:
    runs-on: ubuntu-latest
    env:
      BASEIMAGE: fedora:42
      IMAGETAG: builder-fedora:42
    steps:
      - uses: actions/checkout@master
      - name: update to docker-compose v2
        run: |
          sudo apt-get install -y curl
          sudo curl -SL https://github.com/docker/compose/releases/download/v2.34.0/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version
      - name: create folders as required
        run: |
          mkdir -p rpms specs
          chmod 777 rpms specs
      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: docker/rpmtools
          build-args: |
            BASEIMAGE=${{ env.BASEIMAGE }}
          tags: ${{ env.IMAGETAG }}
      - name: generate specs
        run: |
          docker-compose up specgen --exit-code-from specgen
      - name: build rpms
        run: docker-compose up rpmbuilder --exit-code-from rpmbuilder
