name: Release workflow for tagged versions
on:
  workflow_dispatch:
  release:
    types:
      - published

env:
  COMPOSE_DOCKER_CLI_BUILD: 1

jobs:
  build_rpms:
    strategy:
      matrix:
        arch:
          - arm64
          - amd64
        baseimage:
          - 'rockylinux:8'
          - 'rockylinux:9'
          - 'fedora:39'
          - 'fedora:40'
          - 'fedora:41'
          - 'fedora:42'

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@53851d14592bedcffcf25ea515637cff71ef929a # v3.3.0

      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@6524bf65af31da8d45b59e8c27de4bd072b392f5 # v3.8.0

      - name: update to docker-compose v2
        run: |
          sudo apt-get install -y curl
          sudo curl -SL https://github.com/docker/compose/releases/download/v2.34.0/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: create folders as required
        run: |
          mkdir -p rpms specs
          chmod 777 rpms specs

      - name: generate specs
        run: |
          docker-compose up specgen --exit-code-from specgen

      - name: generate rpms
        run: |
          docker-compose up rpmbuilder --exit-code-from rpmbuilder
        env:
          DOCKER_DEFAULT_PLATFORM: linux/${{ matrix.arch }}
          DOCKER_BUILDKIT: 1
          BASEIMAGE: "${{ matrix.baseimage }}"

      - name: sign rpm's
        run: |
          docker-compose up rpmsigner --exit-code-from rpmsigner
        env:
          DOCKER_DEFAULT_PLATFORM: linux/${{ matrix.arch }}
          DOCKER_BUILDKIT: 1
          BASEIMAGE: "${{ matrix.baseimage }}"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: rpms/*

  download_rpms:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: update to docker-compose v2
        run: |
          sudo apt-get install -y curl
          sudo curl -SL https://github.com/docker/compose/releases/download/v2.34.0/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: create folders as required
        run: |
          mkdir -p rpms
          chmod 777 rpms

      - name: download rpm's
        run: |
          docker-compose up rpmdownloader --exit-code-from rpmdownloader
        env:
          DOCKER_DEFAULT_PLATFORM: linux/${{ matrix.arch }}
          DOCKER_BUILDKIT: 1
          BASEIMAGE: rockylinux:9

      - name: sign rpm's
        run: |
          docker-compose up rpmsigner --exit-code-from rpmsigner
        env:
          DOCKER_DEFAULT_PLATFORM: linux/${{ matrix.arch }}
          DOCKER_BUILDKIT: 1
          BASEIMAGE: rockylinux:9

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: |
            rpms/*
