name: Release workflow for tagged versions
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v0.2.19, v0.2.14a

env:
  GO_VERSION: 1.16

jobs:
  build_rpms:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        spec: ["etcd", "stolon", "wal-g-pg"]
    steps:
    - uses: actions/checkout@v2

    - name: update to docker-compose v2
      run: |
        sudo apt-get install -y curl
        sudo curl -SL https://github.com/docker/compose/releases/download/v2.34.0/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version

    - name: create folders as required
      run: |
        mkdir -p rpms specs
        chmod 777 rpms specs

    - name: generate specs
      run: |
        docker-compose up specgen --exit-code-from specgen

    - name: build RPM package
      id: rpm
      uses: naveenrajm7/rpmbuild@master
      with:
        spec_file: "specs/${{ matrix.spec }}.spec"

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Binary RPM
        path: ${{ steps.rpm.outputs.rpm_dir_path }}

  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create release
        uses: softprops/action-gh-release@v1

